
name: Build
on: [push, pull_request]
env:
  ARDUINO_LIBRARY_ENABLE_UNSAFE_INSTALL: true
  
jobs:
  build:
    name: Build fw
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Arduino CLI
        uses: arduino/setup-arduino-cli@v1
      - name: Build
        run: |
          cd ${GITHUB_WORKSPACE}/fw/forcegauge-esp32/
          echo "VERSION=$(cat ./forcegauge-esp32.ino | grep "#define VERSION" | awk '{ print $3}' | tr -d '"')" >> $GITHUB_ENV
          ./scripts/build.sh

      - name: Save binary
        uses: actions/upload-artifact@v3
        with:
          name: forcegauge-esp32-fw
          path: ${GITHUB_WORKSPACE}/fw/forcegauge-esp32/build/forcegauge-esp32.ino.bin

      - uses: ncipollo/release-action@v1
        with:
          artifacts: "forcegauge-esp32-fw"
          token: ${{ secrets.GITHUB_TOKEN }}

