
name: Build
on: [push]

env:
  ARDUINO_LIBRARY_ENABLE_UNSAFE_INSTALL: true
  
jobs:
  build:
    name: Build fw
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Arduino CLI
        uses: arduino/setup-arduino-cli@v1
      - name: Build
        run: |
          cd ${GITHUB_WORKSPACE}/fw/forcegauge-esp32/
          echo "VERSION=$(cat ./forcegauge-esp32.ino | grep "#define VERSION" | awk '{ print $3}' | tr -d '"')" >> $GITHUB_ENV
          ./scripts/build.sh

      - name: Save binary
        uses: actions/upload-artifact@v3
        with:
          name: forcegauge-esp32-fw
          path: ./fw/forcegauge-esp32/build/forcegauge-esp32.ino.bin

      - name: Release
        uses: softprops/action-gh-release@v1
      # if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ./fw/forcegauge-esp32/build/forcegauge-esp32.ino.bin
      
